### ISSUE TITLE
Minor error in the documentation

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#16]
The [documentation for the rating](https://github.com/Citrinate/FreePackages#minreviewscore) has a minor error.

<details>
  <summary>List of Review Scores</summary>

  Review Score | Description | # of Reviews | % of Positive Reviews 
  --- | --- | --- | ---
  1 | Overwhelmingly Negative | 500+ | 0%-19%
  2 | Very Negative | 50-499 | 0%-19%
  3 | Negative | 1-49 | 0%-19%
  4 | Mostly Negative | 1-49 | 20%-39%
  5 | Mixed | 1-49 | 40%-69%
  6 | Mostly Positive | 1-49 | 70%-79%
  7 | Positive | 1-49 | 80%-100%
  8 | Very Positive | 50-499 | 80%-100%
  9 | Overwhelmingly Positive | 500+ | 80%-100%
</details>

Indeed, check these two games from [the latest Humble Bundle](https://www.humblebundle.com/games/uplifting-adventures-wholesome-games-bundle):

- [**Mail Time**](https://store.steampowered.com/app/1607240/Mail_Time/)
> Recent Reviews: Very Positive (59 reviews) - 91% score
> All Reviews: Very Positive (513 reviews) - 85% score

- [**Smushi Come Home**](https://store.steampowered.com/app/1740300/Smushi_Come_Home/)
> Recent Reviews: Overwhelmingly Positive (130 reviews) - 97% score
> All Reviews: Overwhelmingly Positive (872 reviews) - 99% score

Both games have more than 500 reviews, but only one of them has the "Overwhelmingly Positive" rating.

**Comment by woctezuma** [comment]
I see.

You could remove the number of reviews for:
- Mostly Negative
- Mixed
- Mostly Positive

And maybe show differently the distinction between:
- Very Positive
- Overwhelmingly Positive

**Comment by Citrinate** [comment]
Ah yeah, now it should be right.  I'll keep the 1-49 though as the 10 review minimum only applies to what's displayed on the store.  The plugin can actually see review scores for games with less than 10 reviews.

[Here's](https://steamdb.info/app/1449570/info/) an example of a game with only 8 reviews, but has a `review_score` of 7.  I'm assuming this applies to games with as little as 1 review.
