### ISSUE TITLE
Broken due to major update - 5.5.0.10

### ISSUE THREAD

**Issue by PatrickJnr** [Citrinate/FreePackages#21]
This no longer works since ASF released [5.5.0.10](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.0.10)

**Comment by Citrinate** [comment]
I'll release a new version of the plugin later today.  In the meantime, there's a pre-release version available which may support ASF 5.5.0.10:

https://github.com/Citrinate/FreePackages/releases/tag/1.3.1

**Comment by woctezuma** [comment]
> This no longer works since ASF released [5.5.0.10](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.0.10)

Duplicate of:
- #15

**Comment by Citrinate** [comment]
A proper release with V5.5 support is now posted

**Comment by PatrickJnr** [comment]
Thank you :D
