### ISSUE TITLE
Feature request: Add wishlist / followed games only

### ISSUE THREAD

**Issue by LittleFreak** [Citrinate/FreePackages#23]
please add a filter option, to add only games, which have been followed or wishlisted by the user in the steam store.

**Comment by Citrinate** [comment]
I'll include this in the next release, which will be out sometime next month.  In the meantime if you want you can test the feature using this build: https://github.com/Citrinate/FreePackages/actions/runs/8034266279/artifacts/1272465870

This setting can be added to a filter and is documented as:

#### WishlistOnly

`bool` type with default value of `false`.  If set to `true`, packages must contain an app your account has wishlisted or followed on the Steam storefront or they will not be added to your account.

#### Example: 

```json
"EnableFreePackages": true,
"FreePackagesFilters": [{
  "WishlistOnly": true
}],
```
