### ISSUE TITLE
Latest ASF Update Broke FreePackages

### ISSUE THREAD

**Issue by SpoogLord** [Citrinate/FreePackages#25]
ASF updated today and now I get this error when starting it. Deleting FreePackages fixes the issue

![image](https://github.com/Citrinate/FreePackages/assets/99507754/28a39530-9126-4707-8c9b-0972c42311c0)

**Comment by Citrinate** [comment]
Just released V1.4.2 which works with ASF 6.0.0.3

**Comment by SpoogLord** [comment]
That was interesting to watch, thank you for the quick fix!
Gonna test it before I close jic

**Comment by SpoogLord** [comment]
'Tis not fixed milord - it acts like its working for a few minutes then red text and crash
https://files.catbox.moe/7cq9y1.mp4

**Comment by Citrinate** [comment]
This might be due to using a non-generic version of ASF

Can you try using [V1.4.1](https://github.com/Citrinate/FreePackages/releases/tag/1.4.1)?

**Comment by SpoogLord** [comment]
1.4.1 did the same thing, i tried that while you were posting 1.4.2

**Comment by Citrinate** [comment]
I haven't tried to reproduce this yet, but it looks like it's due to using ASF-win-x64 and not ASF-generic.  I don't have a fix for this right now, but I'll try to get to it within a few days.

**Comment by SpoogLord** [comment]
Same error on generic

**Comment by Citrinate** [comment]
ASF should have a logs.txt file in the directory where it's installed.  Can you post the contents of the logs.txt file from when you were running ASF-generic.

**Comment by SpoogLord** [comment]
[log.txt](https://github.com/Citrinate/FreePackages/files/14547343/log.txt)

**Comment by Citrinate** [comment]
> ArchiSteamFarm-592|INFO|ASF|InitCore() ArchiSteamFarm V6.0.0.3 (**win-x64**/3c050fb5aa76443c96dc927a1da3ae0c 

I see you're running ASF from a folder called `ASF-generic`, but the version you're running still seems to be `win-x64`

**Comment by SpoogLord** [comment]
I downloaded a new copy of asf, the one labeled ASF-generic on the repo

**Comment by SpoogLord** [comment]
from here
https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/6.0.0.3

**Comment by SpoogLord** [comment]
wait, I'm realizing i messed something up. let me get back to you on that

**Comment by SpoogLord** [comment]
Alright, it seems somehow ArchiSteamFarm.cmd from the generic copy was somehow loading my x64 installation? Which idek how that works, they're in completely different folders. But I got it to actually run generic with the plugin, its been 5 minutes without crashing so I'm guessing it works fine on generic. 
Thank you for the quick support and sorry for being dumb!
