### ISSUE TITLE
qstatus is unknown

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#28]
`queuestatus`, `qstatus`, `qsa` are unknown commands.

```
ASF 6.0.0.3
FreePackages 1.4.2
```

**Comment by Citrinate** [comment]
Are you using ASFEnhance?

I can reproduce this on ASF-generic, but strangely only when ASFEnhance is also installed.  In the meantime, [V1.4.1](https://github.com/Citrinate/FreePackages/releases/tag/1.4.1) of the plugin is the same as V1.4.2, but without any ASFEnhanced features.

**Comment by woctezuma** [comment]
> Are you using ASFEnhance?

Yes, [the version 2.1.0.0](https://github.com/chr233/ASFEnhance/releases/tag/2.1.0.0).

**Comment by Citrinate** [comment]
The actual steps to reproduce this error require FreePackages, ASFEnhance, and BoosterManager all to be installed.  Under these conditions, potentially none of the FreePackages commands will work.  This seems to me to actually be an issue with ASFEnhance.  ASFEnhance is set up to intercept commands for the purpose of enacting it's `DisabledCmds` config setting, but it's not correctly passing those commands to the appropriate plugin.

My solution is to remove support for ASFEnhance's `DisabledCmds` config setting on all of my plugins.  I don't plan on adding this support back in in the future as it has the potential to break this plugin, and also I don't consider it to be all that useful. 
 `PLUGINSUPDATE` command support should be unaffected.

If you'd like to test this change, here's the current builds: [FreePackages V1.4.3](https://github.com/Citrinate/FreePackages/actions/runs/8225185911/artifacts/1313293163), [BoosterManager V2.8.4](https://github.com/Citrinate/BoosterManager/actions/runs/8225186296/artifacts/1313292703)

**Comment by woctezuma** [comment]
> If you'd like to test this change, here's the current builds: [FreePackages V1.4.3](https://github.com/Citrinate/FreePackages/actions/runs/8225185911/artifacts/1313293163), [BoosterManager V2.8.4](https://github.com/Citrinate/BoosterManager/actions/runs/8225186296/artifacts/1313292703)

These builds work.
