### ISSUE TITLE
[Feature Request] MinReviewScore Delay

### ISSUE THREAD

**Issue by PhasecoreX** [Citrinate/FreePackages#30]
Hello! I noticed that the game [Content Warning](https://steamdb.info/app/2881650/subs/) came out today, along with a No Cost promotional package available for 24 hours. I assumed that FreePackages would pick this up, but it didn't. These are my settings:
```
"EnableFreePackages": true,
  "FreePackagesFilters": [
    {
      "Types": [
        "DLC"
      ]
    },
    {
      "Types": [
        "Game"
      ],
      "Languages": [
        "english"
      ],
      "MinReviewScore": 6,
      "IgnoreFreeWeekends": true,
      "NoCostOnly": true
    }
  ]
```
The only part of the config that might be ignoring the game would be the `MinReviewScore`, as at the time of processing, my guess is that there were zero reviews.

My feature request is for there to be some sort of cache that holds onto free packages that don't have the required review score but otherwise match on all the other settings, so that perhaps in a couple of hours it'll have the target review score and can be added. In this case, it's at about 91%, so well over the threshold for this config. However, since it was checked right when it was made available with no reviews, it won't be added (unless another package change happens between now and the 24 hours later when it becomes not free).

Also, I am assuming that this is the reason it wasn't added. If I missed something or configured something wrong please let me know. My guess is that if this was a highly-rated existing game that went on sale for 24 hours it would have been picked up just fine. But it's this edge case where a brand new game doesn't have enough reviews to get picked up.

**Comment by woctezuma** [comment]
For this specific scenario, I suggest to remove your filter for `MinReviewScore`, as there are few `No Cost` packages anyway. It seems to me that there is not much point adding filters on top of `No Cost`.

As for a fix, the simplest solution would probably to allow packages without a review score rather than to introduce an arbitrary delay.

**Comment by PhasecoreX** [comment]
Ah, I didn't realize that it was so few games/applications. I also kinda figured some delay thing would have been a decent architectural change/overkill and might not have been worth it anyway. I'll just remove the `MinReviewScore` then for this filter. Thanks!

**Comment by Citrinate** [comment]
True, a delay would have been quite the hassle to implement.  While I agree that just not using `MinReviewScore` here is a good enough solution, I've decided to add a `MinDaysOld` filter which could help here while also being generally more useful:

> #### MinDaysOld
> 
> `uint` type with default value of `0`.  Packages must contain an app with a Steam release date newer than this many days or they will not be added to your account.  You can leave this at `0` to allow for all values.

You could then change the original config to only ignore the review score on `NoCost` packages if they have a game which was released in the last 24 hours.

```json
"FreePackagesFilters": [
    {
      "Types": [
        "DLC"
      ]
    },
    {
      "Types": [
        "Game"
      ],
      "Languages": [
        "english"
      ],
      "MinReviewScore": 6,
      "IgnoreFreeWeekends": true,
      "NoCostOnly": true
    },
    {
      "Types": [
        "Game"
      ],
      "Languages": [
        "english"
      ],
      "MinDaysOld": 1,
      "IgnoreFreeWeekends": true,
      "NoCostOnly": true
    }
  ]
```

If you'd like to test this feature you can download the latest build here: [FreePackages V1.5.0.0](https://github.com/Citrinate/FreePackages/actions/runs/8676241950/artifacts/1411472478)

**Comment by PhasecoreX** [comment]
Sorry I took a month to reply to this... but thank you for this new `MinDaysOld` option! I have updated my config to what you have shown above and loaded the latest build. It'll probably take a while to actually test this, due to no cost games being rare in the first place. I'll keep watch over free game sources and what ends up being claimed automatically. Thank you again!
