### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LeaLangley** [Citrinate/FreePackages#37]
are "NoCostOnly" games those that are "Free To Keep" , so if picked up in time , its a game that usually cost money but we can keep it for free.

**Comment by LeaLangley** [comment]
just confused on what the correct configuration is, to auto collect those games.

**Comment by woctezuma** [comment]
> are "NoCostOnly" games those that are "Free To Keep" , so if picked up in time , its a game that usually cost money but we can keep it for free.

Yes, but some "FreeOnDemand" games also work like this.
The good thing with NoCost games is that they increment the counter of your library.

**Comment by LeaLangley** [comment]
alright that sounds good to me , thanks for the quick reply and clarifying this , have a great rest of your day/night.
