### ISSUE TITLE
1.5.0.1 doesn't connect to steamdb free packages

### ISSUE THREAD

**Issue by kotenok2000** [Citrinate/FreePackages#38]
It gives "Failed to connect to ASF. Please click on "Settings" and verify your server and port."

**Comment by Citrinate** [comment]
This doesn't seem like an issue to me.  You need to do what the message is telling you, which is not something I can help you with.

**Comment by kotenok2000** [comment]
I have checked it. it is still http://localhost:1242
![image](https://github.com/Citrinate/FreePackages/assets/8822292/c19ba2d9-293f-4c50-bca6-2e67b4635c55)

**Comment by kotenok2000** [comment]
Maybe something was broken by latest chrome update?
