### ISSUE TITLE
Error with FreePackages plugin in latest version

### ISSUE THREAD

**Issue by Nipponshin** [Citrinate/FreePackages#41]
Hello, I am having the following error with the latest version of FreePackages and ASF:

`2024-07-05 20:50:41|ArchiSteamFarm-35252|ERROR|ASF|CreateOrLoad() System.Text.Json.JsonException: '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.`

If I remove the FreePackages plugin, the error is gone.

I have attached the log file too, please let me know if anything else is needed.
[log.txt](https://github.com/user-attachments/files/16114358/log.txt)

**Comment by Citrinate** [comment]
In the `asf/config` folder there should be the file: `FreePackages.cache`.  Could you upload this file?

The error could probably be resolved by deleting `FreePackages.cache`.

**Comment by Nipponshin** [comment]
Hello @Citrinate,

I tried to attach the file here, but I get the following from GitHub, and I am unable to do so:

> We don’t support that file type.
> 
> Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

I have uploaded it [here](https://drive.google.com/file/d/1R3AECDdgLyPdgYB0Y3Uch56gxmpSnhxz/view?usp=sharing) so you can download it.

Should I proceed to delete it from my end to test?

**Comment by Citrinate** [comment]
Yes you can delete the file, which got corrupted somehow, and I expect that should be enough to resolve the issue.

**Comment by Nipponshin** [comment]
Thanks, @Citrinate!

I confirm that everything is working as expected after deleting the `FreePackages.cache` file.

I am marking this as solved.
