### ISSUE TITLE
Clarify FreePackagesPerHour

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#43]
Nowadays, `FreePackagesPerHour` specifies the number of packages which can be activated in a 90-minute-long time window. The name is only kept for legacy purposes. Is that correct?

**Comment by Citrinate** [comment]
Completely missed those references, thanks for pointing it out.  I've added `FreePackagesLimit` as an alias for  `FreePackagesPerHour`, and will keep `FreePackagesPerHour` as to not break anyone's configs. 

I'll leave this open as there's still references in the README to `FreePackagesPerHour` that I can't change yet as the current release doesn't support `FreePackagesLimit`.
