### ISSUE TITLE
Error with linux x86 version

### ISSUE THREAD

**Issue by Nemoron** [Citrinate/FreePackages#52]
The plugin worked fine when I last used asf about a week ago. 
When I tried starting asf today, I get the following error unless I remove the plugin.

ERROR|ASF|InitPlugins() System.TypeLoadException: Could not load type 'System.Diagnostics.DebuggerNonUserCodeAttribute' from assembly 'System.Runtime

[log.txt](https://github.com/user-attachments/files/16911713/log.txt)

**Comment by Citrinate** [comment]
Looks like a duplicate of #45.  Make sure you're using the latest version of the plugin: V1.5.2.0

**Comment by Nemoron** [comment]
Oh sry. ^^
Btw thank you for your work. :)
