### ISSUE TITLE
Do package filters impact performance?

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#6]
You allow to use package filters, which can be handy, e.g. if someone is only interested in F2P games which support Steam Trading Cards. However, I would like to know if package filters impact performance.

Does this lead to more requests being made for instance? In terms of web requests, is the most light-weight method to have no configuration setting except `"EnableFreePackages": true,`. Or is all the package information fetched anyway in the first place?

**Comment by Citrinate** [comment]
There's some optimizations I can do to reduce the number of requests if no bots are using filters, but only with regards to subs and not for apps.  When these optimizations are implemented though, we're talking about an often 1 request difference between using filters and not using filters.

**Comment by woctezuma** [comment]
Thank you for the information! Then I can use filters without afterthought!
