### ISSUE TITLE
UrlgetJsonObjectwithsession

### ISSUE THREAD

**Issue by Teufel0406** [Citrinate/FreePackages#60]
![image](https://github.com/user-attachments/assets/b3031aad-b56d-47fc-9add-9087def052e2)

**Comment by Citrinate** [comment]
This is usually an error that can be ignored.  It tends to occur when a bot is offline.

Still, I've made some changes which should reduce how often this appears.

If you'd like to test this change you can download the latest build here: https://github.com/Citrinate/FreePackages/actions/runs/11087816904/artifacts/1991401426
