### ISSUE TITLE
Feature Request: Only activate DLC for apps I already own

### ISSUE THREAD

**Issue by mocmocamoc** [Citrinate/FreePackages#61]
At the moment, including "DLC" in the Types will activate free packages that contain both DLC and also the the app to which the DLC belongs. It'd be good if there was a way to only activate a package if the DLC in that package belongs to an app that I already own. This is similar to what the SteamDB free packages page does when you select "only view content for your owned games".

**Comment by Citrinate** [comment]
Don't quite understand this.  Can you give an example of a package you don't think should have been activated, along with your `FreePackagesFilters` config setting.

Naturally you can only activate DLC for apps you own, and so the plugin wont even attempt to activate a DLC-only package if you don't own the required app.  If there's a package that contains an app along with DLC for that app, the plugin checks that both of these items pass your filters, and if they do only then it will activate that package.

Or are you maybe talking about free soundtracks?  These technically aren't DLC and don't require you own the base app.

**Comment by mocmocamoc** [comment]
There's nothing that's working incorrectly at the moment. But if a user's goal is just to automatically collect free DLC for apps that they already own, then there's currently no way to do that without also activating free packages that contain both an app and DLC for that app. If there was an option that caused the plugin to activate DLC for apps the user already owns, but not to activate packages containing previously unowned apps and their DLC, then it would make that use case possible.

**Comment by Citrinate** [comment]
I made a mistake in my earlier post.  When a package has multiple apps in it, the plugin will only try to activate it if at least 1 app passes the filter, and 0 apps are excluded by the filter.  This config setting will therefore activate all packages with DLC, even DLC+App packages:

```json
"FreePackagesFilters": [{
  "Types": ["DLC"],
}]
```

If you want DLC packages, but not DLC+App packages, this filter should do that:

```json
"FreePackagesFilters": [{
  "Types": ["DLC"],
  "IgnoredTypes": ["Game", "Application"],
}]
```

**Comment by mocmocamoc** [comment]
That's great - I didn't realise the filters worked like that. Thanks for explaining!
