### ISSUE TITLE
Claim Progress Info

### ISSUE THREAD

**Issue by LeaLangley** [Citrinate/FreePackages#62]
it would be cool if the plugin could report the progress of the ID activation.
for example if i have a larger list of ID's , it would be cool to know how far it already progressed.
for example we have `ProcessQueue() Pausing free package activations until 10:27:03 AM`
it would be cool if it could as addition say:
- how many it already activated.
- how many it still needs to activate.
- how much % is already activated.

**Comment by Citrinate** [comment]
There's a command for checking stuff like this: `queuestatus`

**Comment by LeaLangley** [comment]
oh thank you very much , ive overseen that
