### ISSUE TITLE
[Question] Multiple package filter / NoCostOnly

### ISSUE THREAD

**Issue by LeaLangley** [Citrinate/FreePackages#64]
Is it possible to use multiple package filter with one of them no cost only ?
for example
```
"FreePackagesFilters": [{
  "NoCostOnly": true,
},{
  "Types": ["Game"],
  "Tags": [4604],
}],
```
would it add any "NoCostOnly" games, and in addition any free game with tag 4604 ?

sorry for the question just making sure before i consider using it.

**Comment by Citrinate** [comment]
Yes, it should work how you described it.

**Comment by LeaLangley** [comment]
thank you very much for confirming.
love that plugin <3
