### ISSUE TITLE
Missing types in IgnoredTypes

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/FreePackages#9]
In [`IgnoredTypes`](https://github.com/Citrinate/FreePackages#ignoredtypes), a few types which are listed [on SteamDB](https://steamdb.info/instantsearch/) are missing. I don't know if this matters.

In the README, there are 6 types:

> The available types for filtering are: `Game`, `Application`, `Tool`, `Demo`, `DLC`, `Music`

In SteamDB's instant search, there are 4 additional types:

> `Video`, `Series`, `Unknown` and `Hardware`.

![Picture](https://i.imgur.com/RBNNMnU.png)

This means that if one wants to focus on the type `Game`, then they should ignore the other 9 types:

```json
"IgnoredTypes": [
  "Application",
  "Demo",
  "DLC",
  "Hardware",
  "Music",
  "Series",
  "Tool",
  "Unknown",
  "Video"
],
```

**Comment by Citrinate** [comment]
There's no restrictions to what you can add to `IgnoredTypes`, this is just a README thing.

There's even more types than that, such as Plugin and Comic.  I only intended to list the types that actually had free packages, which is the types that have entries when searching for `extended_isfreeapp` equals `1`.  [Video](https://steamdb.info/search/?a=app_keynames&type=13&keyname=243&operator=3&keyvalue=1) should definitely be there.  Arguably Unknown should be there also, but it seems the only 2 [free Unknowns](https://steamdb.info/search/?a=app_keynames&type=0&keyname=243&operator=3&keyvalue=1) are unavailable.

It seems to make sense for there to be a `Types` filter for people who only want specific types.

I might as well also add `IgnoredCategories` and `ContentDescriptors` filters.

**Comment by woctezuma** [comment]
> It seems to make sense for there to be a `Types` filter for people who only want specific types.
> 
> I might as well also add `IgnoredCategories` and `ContentDescriptors` filters.

Yes, that was my thought as well, though I don't know if it is worth the effort for you.

Do as you think it is best. ❤️

**Comment by Citrinate** [comment]
Added, if you want you can test it here: [FreePackages V1.2.0.zip](https://github.com/Citrinate/FreePackages/files/12910790/FreePackages.zip)

The syntax is the same as in your comment:

> ```json
> "FreePackagesFilter": {
>   "Types": [
>     "Game"
>   ],
> },
> ```

**Comment by woctezuma** [comment]
Thank you!
